name: ci-workflow
on:
  pull_request:

jobs:
  checkout-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - run: npm test
